version: '3.8'

services:
  php81:
    build:
      context: .
      target: app_php
    image: php81/php:dev
    restart: on-failure
    networks:
      RAS_PROD1:
          ipv4_address: 192.168.1.7
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=localhost
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/app:rw,cached
      - ./var:/app/var
  nginx:
    build:
      context: .
      target: app_nginx
    image: nginx:dev
    restart: on-failure
    networks:
      RAS_PROD1:
          ipv4_address: 192.168.1.6
    depends_on:
      - php81
    volumes:
      - ./public:/app/public:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
networks:
    RAS_PROD1:
        name: monolithic_api_RAS_PROD
        external: true
volumes:
  db-data:
  var: