version: '3.8'

services:
  phpservice:
    container_name: hello_php
    build:
      context: .
      target: app_php
    image: php81/php:dev
    restart: on-failure
    networks:
      - wironet
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=localhost
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/app:rw,cached
      - ./var:/app/var
  hello:
    container_name: hello
    build:
      context: .
      target: app_nginx
    image: nginx:dev
    restart: on-failure
    networks:
      - wironet
    depends_on:
      - phpservice
    volumes:
      - ./public:/app/public:ro
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d:rw
    ports:
      - 8093:80
networks:
    wironet:
        external: true


volumes:
  db-data:
  var: