version: '3.8'

services:
  php81:
    build:
      context: .
      target: app_php
    image: php81/php:dev
    restart: on-failure
    networks:
      NET_WIRO_SBX:
          ipv4_address: 192.168.0.3
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=localhost
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - .:/app:rw,cached
      - ./var:/app/var
  payments:
    build:
      context: .
      target: app_nginx
    image: nginx:dev
    restart: on-failure
    networks:
      NET_WIRO_SBX:
          ipv4_address: 192.168.0.4
    depends_on:
      - php81
    volumes:
      - ./public:/app/public:ro
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d:rw
    ports:
      - 8090:80
networks:
    NET_WIRO_SBX:
        name: wironet
        external: true

volumes:
  db-data:
  var: